deploy:
  provider: pypi
  user: edx
  distributions: sdist bdist_wheel
  on:
    tags: true
    condition: "$TOXENV=quality"
  password:
    secure: uuJV7B4OBPs1U/LlfFFaFo/aUM8FLXuJB3+SCIxdWCXwmfY6GPQOs7BIPfUlXS+THHnszQ0/22T6RZa9/Db+tIoI6NGeGhMzDSOcU8AQmJ+aSILGP/HfMYVF2n+nNjs39nHro6m43ce43RC+1YROqfXLX3t6BlgRGUd5Y0HDRbXEaCpoDXsOnm1neXTadLDuEYVkTW3EwPbyK2vFREuevNPo8RPgt6Z4YHBJ43QxERTGWaov5HocEjFm3RnzatZto/h1QdgAipjtRdTpcRDRve9bUawMQXghYJbrnYPoIlNpXmlZQvEBBiq6NdPP+bGa0EURGNhxpsCOl2IDjaGBHQ3gThY+RxMBT6cjAO62AxYwq277lG/6JsbW8dr5GpVp/uk+K8+ddtBtT2D4sEfSUvSk+ntZdtaV9x7wE8v7L2hXuSEADPRRqUdSbUj1WkUAXXS6cb8hGLrYy3ej54gq/4dGz/mm/6Pqwt2oQe/Oa27qcz1FA0yXb90hIkclZAowNNGyphMn8kGDggUycD1tSj50dK29y0wGssz2IFDUF5ek7RHuOkMgrmO2u8zJbdqz1E6/41ZZJ3+Lch8OQh6w4OXgbeWHTyBhcMMmPKCWzQO/UTT+UhKMi7Igk5Dlt8wfCmdFtYpALql2nkRzK/IhQ0DGKp+2E591tOx03jqcfSY=
